import type { EraMeta } from '../types'

const meta: EraMeta = {
  id: '10',
  slug: '10-skeuomorphism',
  title: 'Skeuomorphism & texture',
  years: '2007–2013',
  summary:
    'When touchscreens arrived, interfaces borrowed the look of real objects so people knew what to tap: stitched leather, torn paper, brass switches and glossy app icons.',
  context: {
    screens: 'The 3.5-inch 320×480 iPhone, then 1024×768 tablets, then the first 2× “retina” displays (2010)',
    connection: 'Home broadband and 3G; image sprites and CSS3 gradients replaced sliced background JPEGs',
    browsers: 'Mobile Safari and Android WebKit, Safari 4–6, Chrome, Firefox 3.5–4; IE8 still needed fallback PNGs',
  },
  traits: [
    { id: 'texture', label: 'Linen, wood and leather textures' },
    { id: 'stitch', label: 'Stitched leather with dashed “thread” borders' },
    { id: 'letterpress', label: 'Letterpress text with inset text-shadow' },
    { id: 'gloss', label: 'Glossy, rounded app icon with a highlight sheen' },
    { id: 'paper', label: 'Paper cards with torn, deckled edges' },
    { id: 'script', label: 'Handwritten script fonts' },
    { id: 'curl', label: 'Page-curl corner' },
    { id: 'controls', label: 'Physical-looking switches, keys and knobs' },
  ],
  tech: [
    'CSS3 gradients, box-shadow, text-shadow and border-radius (2009–2011) replacing sliced images',
    'Tiling noise textures, here generated with an SVG feTurbulence filter in a data URI',
    'Retina-ready @2x image sprites and, later, icon fonts',
    'Dashed borders and outline-offset faking stitched thread',
  ],
  thenVsNow:
    'iOS 7 (2013) stripped the leather and linen for flat colour; the idea survives as subtle depth in Material shadows and neumorphism experiments.',
  snippets: [
    { file: 'era.css', lang: 'css', caption: 'Stitched leather: a dashed border inside a gradient', region: 'leather' },
    { file: 'era.css', lang: 'css', caption: 'Letterpress: one light shadow below, one dark above', region: 'letterpress' },
    { file: 'demo.html', lang: 'html', caption: 'A glossy app icon drawn in SVG', region: 'icon' },
    { file: 'era.client.ts', lang: 'typescript', caption: 'A dimmer knob mapped to a 270° sweep', region: 'knob' },
  ],
  sources: [
    { label: 'Skeuomorph (Wikipedia)', url: 'https://en.wikipedia.org/wiki/Skeuomorph' },
    { label: 'iOS 7 (Wikipedia)', url: 'https://en.wikipedia.org/wiki/IOS_7' },
    { label: 'text-shadow (MDN)', url: 'https://developer.mozilla.org/en-US/docs/Web/CSS/text-shadow' },
    { label: '<feTurbulence> (MDN)', url: 'https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feTurbulence' },
  ],
  recreated: [
    'Period sites used tiled PNG/JPEG textures; here the grain is generated by an SVG noise filter so the room ships no image files.',
    'The torn paper edge is a CSS mask; at the time it was usually a transparent PNG border image.',
  ],
}

export default meta
